import React, { useState, useEffect } from 'react';
import { Sidebar } from './components/Sidebar';
import { Dashboard } from './pages/Dashboard';
import { BankMaster } from './pages/BankMaster';
import { Scheduler } from './pages/Scheduler';
import { ActionCenter } from './pages/ActionCenter';
import { Insights } from './pages/Insights';
import { Settings } from './pages/Settings';
import { Login } from './pages/Login';
import { MOCK_USERS } from './constants';
import { BankAccount, BankStatus, User, ActivityLog, SyncSchedule } from './types';
import { subscribeToAuthChanges, logout } from './services/authService';
import * as dbService from './services/dbService';

const App: React.FC = () => {
  // Auth State
  const [currentUser, setCurrentUser] = useState<User | null>(null);
  const [loading, setLoading] = useState(true);

  // App Data State
  const [currentPage, setCurrentPage] = useState('dashboard');
  const [accounts, setAccounts] = useState<BankAccount[]>([]);
  const [schedules, setSchedules] = useState<SyncSchedule[]>([]);
  const [logs, setLogs] = useState<ActivityLog[]>([]);
  const [users, setUsers] = useState<User[]>([]);

  // Services
  useEffect(() => {
    const unsubscribe = subscribeToAuthChanges((user) => {
      setCurrentUser(user);
      setLoading(false);
    });
    return () => unsubscribe();
  }, []);

  useEffect(() => {
    if (currentUser) {
      const fetchData = async () => {
        try {
          const fetchedAccounts = await dbService.getAccounts();
          setAccounts(fetchedAccounts);
          const fetchedSchedules = await dbService.getSchedules();
          setSchedules(fetchedSchedules);
          const fetchedLogs = await dbService.getLogs();
          setLogs(fetchedLogs);
          // Fetch Managed Users
          const fetchedUsers = await dbService.getUsers();
          setUsers(fetchedUsers.length > 0 ? fetchedUsers : MOCK_USERS);
        } catch (error) {
          console.error("Failed to fetch data:", error);
        }
      };
      fetchData();
    }
  }, [currentUser]);

  // Counts
  const pendingOtpCount = accounts.filter(a => a.status === BankStatus.OTP_REQUIRED).length;

  // Actions
  const handleLogin = (user: User) => {
    setCurrentUser(user);
    setCurrentPage('dashboard');
  };

  const handleLogout = async () => {
    setCurrentUser(null);
    try {
      await logout();
    } catch (error) {
      console.error("Logout failed", error);
    }
  };

  // --- Bank Account Management ---
  const addAccount = async (acc: BankAccount) => {
    try {
      // @ts-ignore - id will be generated by firestore
      const { id, ...accData } = acc;
      const newAcc = await dbService.addAccount(accData);
      setAccounts(prev => [...prev, newAcc as BankAccount]);
      await dbService.addLog({
        bankName: acc.bankName,
        action: `Added new bank: ${acc.bankName}`,
        status: 'Success',
        triggeredBy: currentUser?.name || 'Unknown'
      });
    } catch (error) {
      console.error("Error adding account:", error);
      alert("Failed to add account: " + (error instanceof Error ? error.message : "Unknown error"));
      throw error; // Propagate to caller (BankMaster)
    }
  };

  const updateAccount = async (updatedAcc: BankAccount) => {
    try {
      // @ts-ignore
      const { id, ...updates } = updatedAcc;
      await dbService.updateAccount(id, updates);
      setAccounts(prev => prev.map(a => a.id === updatedAcc.id ? updatedAcc : a));
      await dbService.addLog({
        bankName: updatedAcc.bankName,
        action: `Updated bank details: ${updatedAcc.bankName}`,
        status: 'Success',
        triggeredBy: currentUser?.name || 'Unknown'
      });
    } catch (error) {
      console.error("Error updating account:", error);
      alert("Failed to update account: " + (error instanceof Error ? error.message : "Unknown error"));
      throw error;
    }
  };

  const removeAccount = async (id: string) => {
    try {
      // Note: Delete method needs to be implemented in dbService first if not exists, 
      // but for now we assume it exists or I will add it.
      // Checking dbService.ts... deleteDoc exists in imports but not exported function.
      // I will need to update dbService.ts first. Awaiting that step.
      // For now, I will comment out the actual db delete call until next step.
      // await dbService.deleteAccount(id); 

      setAccounts(prev => prev.filter(a => a.id !== id));
      setSchedules(prev => prev.filter(s => s.bankId !== id));
      await dbService.addLog({
        bankName: 'System',
        action: 'Removed bank account',
        status: 'Success',
        triggeredBy: currentUser?.name || 'Unknown'
      });
    } catch (error) {
      console.error("Error deleting account:", error);
    }
  };

  // --- Schedule Management ---
  const toggleSchedule = (id: string) => {
    // Optimistic update
    setSchedules(prev => prev.map(s => s.id === id ? { ...s, isActive: !s.isActive } : s));
    const schedule = schedules.find(s => s.id === id);
    if (schedule) {
      // Toggle the CURRENT state inverse, because state update above is async/batched 
      // effectively next render. Safest is to toggle the original found value.
      dbService.updateSchedule(id, { isActive: !schedule.isActive });
    }
  };

  const addSchedule = async (schedule: SyncSchedule) => {
    try {
      // @ts-ignore
      const { id, ...scheduleData } = schedule;
      const newSchedule = await dbService.addSchedule(scheduleData);
      setSchedules(prev => [...prev, newSchedule as SyncSchedule]);
      await dbService.addLog({
        bankName: 'Scheduler',
        action: 'Created new sync schedule',
        status: 'Success',
        triggeredBy: currentUser?.name || 'Unknown'
      });
    } catch (error) {
      console.error("Error adding schedule:", error);
    }
  };

  const updateSchedule = async (updatedSchedule: SyncSchedule) => {
    try {
      // @ts-ignore
      const { id, ...updates } = updatedSchedule;
      await dbService.updateSchedule(id, updates);
      setSchedules(prev => prev.map(s => s.id === updatedSchedule.id ? updatedSchedule : s));
      await dbService.addLog({
        bankName: 'Scheduler',
        action: 'Updated sync schedule configuration',
        status: 'Success',
        triggeredBy: currentUser?.name || 'Unknown'
      });
    } catch (error) {
      console.error("Error updating schedule:", error);
    }
  };

  const removeSchedule = async (id: string) => {
    try {
      await dbService.deleteSchedule(id);
      setSchedules(prev => prev.filter(s => s.id !== id));
      await dbService.addLog({
        bankName: 'Scheduler',
        action: 'Deleted sync schedule',
        status: 'Success',
        triggeredBy: currentUser?.name || 'Unknown'
      });
    } catch (error) {
      console.error("Error deleting schedule:", error);
    }
  };

  const resolveOtp = async (bankId: string) => {
    // Update local state first
    setAccounts(prev => prev.map(a =>
      a.id === bankId ? { ...a, status: BankStatus.CONNECTED, lastSync: 'Just now' } : a
    ));

    // Persist to DB
    try {
      await dbService.updateAccount(bankId, { status: BankStatus.CONNECTED, lastSync: new Date().toISOString() });
      setTimeout(async () => {
        alert("OTP Verified. Download initiated.");
        await dbService.addLog({
          bankName: 'Action Center',
          action: 'OTP Verified & Download Started',
          status: 'Success',
          triggeredBy: currentUser?.name || 'Unknown'
        });
      }, 500);
    } catch (error) {
      console.error("Error verifying OTP:", error);
    }
  };

  const handleManualDownload = (bankIds: string[]) => {
    const bankNames = accounts.filter(a => bankIds.includes(a.id)).map(a => a.bankName);

    // Update logs
    const newLogs: ActivityLog[] = bankNames.map((name, idx) => ({
      id: "pending-" + Date.now() + idx,
      bankName: name,
      action: 'Manual Download Triggered',
      timestamp: 'Just now',
      status: 'Pending',
      triggeredBy: currentUser?.name || 'Unknown'
    }));
    setLogs(prev => [...newLogs, ...prev]);

    // Simulate success after delay
    setTimeout(() => {
      // Update Logs in DB
      newLogs.forEach(async (log) => {
        await dbService.addLog({
          bankName: log.bankName,
          action: log.action,
          status: 'Success',
          triggeredBy: log.triggeredBy
        });
      });

      // Update Accounts Last Sync
      bankIds.forEach(async (id) => {
        await dbService.updateAccount(id, { lastSync: new Date().toISOString() });
      });

      setLogs(prev => prev.map(l =>
        newLogs.find(nl => nl.id === l.id) ? { ...l, status: 'Success', timestamp: 'Just now' } : l
      ));

      setAccounts(prev => prev.map(a =>
        bankIds.includes(a.id) ? { ...a, lastSync: 'Just now' } : a
      ));
    }, 3000);
  };

  // User Management
  const addUser = async (user: User) => {
    try {
      // @ts-ignore
      const { id, ...userData } = user;
      const newUser = await dbService.addUser(userData);
      setUsers(prev => [...prev, newUser as User]);
      await dbService.addLog({
        bankName: 'Settings',
        action: `Added new user: ${user.name}`,
        status: 'Success',
        triggeredBy: currentUser?.name || 'Unknown'
      });
    } catch (error) {
      console.error("Error adding user:", error);
    }
  };

  const removeUser = async (id: string) => {
    try {
      await dbService.deleteUser(id);
      setUsers(prev => prev.filter(u => u.id !== id));
      await dbService.addLog({
        bankName: 'Settings',
        action: 'Removed user',
        status: 'Success',
        triggeredBy: currentUser?.name || 'Unknown'
      });
    } catch (error) {
      console.error("Error removing user:", error);
    }
  };

  const addLog = (action: string, context: string) => {
    const newLog: ActivityLog = {
      id: Date.now().toString(),
      bankName: context,
      action: action,
      timestamp: 'Just now',
      status: 'Success',
      triggeredBy: currentUser?.name
    };
    setLogs(prev => [newLog, ...prev]);
  };

  // Router logic
  const renderPage = () => {
    if (!currentUser) return null; // Should be handled by Login view

    switch (currentPage) {
      case 'dashboard':
        return <Dashboard accounts={accounts} logs={logs} setPage={setCurrentPage} onManualDownload={handleManualDownload} />;
      case 'bank-master':
        return currentUser.role === 'Downloader'
          ? <Dashboard accounts={accounts} logs={logs} setPage={setCurrentPage} onManualDownload={handleManualDownload} /> // Redirect if unauthorized
          : <BankMaster
            accounts={accounts}
            addAccount={addAccount}
            updateAccount={updateAccount}
            removeAccount={removeAccount}
          />;
      case 'scheduler':
        return currentUser.role === 'Downloader'
          ? <Dashboard accounts={accounts} logs={logs} setPage={setCurrentPage} onManualDownload={handleManualDownload} />
          : <Scheduler
            schedules={schedules}
            accounts={accounts}
            toggleSchedule={toggleSchedule}
            addSchedule={addSchedule}
            updateSchedule={updateSchedule}
            removeSchedule={removeSchedule}
          />;
      case 'action-center':
        return <ActionCenter accounts={accounts} resolveOtp={resolveOtp} />;
      case 'insights':
        return <Insights />;
      case 'settings':
        return <Settings users={users} currentUser={currentUser} addUser={addUser} removeUser={removeUser} />;
      default:
        return <Dashboard accounts={accounts} logs={logs} setPage={setCurrentPage} onManualDownload={handleManualDownload} />;
    }
  };

  if (loading) {
    return <div className="min-h-screen bg-slate-950 flex items-center justify-center text-white">Loading...</div>;
  }

  if (!currentUser) {
    return <Login onLogin={() => { }} />; // Handler is now redundant due to subscription
  }

  return (
    <div className="flex min-h-screen bg-slate-950 text-slate-100 font-sans selection:bg-blue-500/30">
      <Sidebar
        currentPage={currentPage}
        setPage={setCurrentPage}
        pendingOtpCount={pendingOtpCount}
        currentUser={currentUser}
        onLogout={handleLogout}
      />

      <main className="flex-1 ml-64 p-8">
        <header className="flex justify-between items-center mb-8">
          <div>
            <h1 className="text-2xl font-bold text-white capitalize">{currentPage.replace('-', ' ')}</h1>
            <p className="text-slate-500 text-sm">Welcome back, {currentUser.name}</p>
          </div>

          <div className="absolute left-1/2 top-8 transform -translate-x-1/2 -translate-y-1/2 hidden lg:block">
            <h2 className="text-xl font-bold text-slate-200 tracking-widest uppercase">Wellknown Polyesters Limited</h2>
          </div>

          <div className="flex items-center gap-4">
            <div className="bg-slate-800 rounded-full px-4 py-1.5 border border-slate-700 flex items-center gap-2">
              <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse"></span>
              <span className="text-xs font-medium text-slate-300">System Online</span>
            </div>
            <div className="w-10 h-10 rounded-full bg-gradient-to-tr from-blue-500 to-purple-500 flex items-center justify-center text-white font-bold text-sm shadow-lg shadow-blue-500/20">
              {currentUser.avatar}
            </div>
          </div>
        </header>

        <div className="animate-in fade-in duration-500">
          {renderPage()}
        </div>
      </main>
    </div>
  );
};

export default App;