type User @table(key: ["id"]) {
  id: String!
  displayName: String!
  email: String!
  photoUrl: String
  role: String!
  avatar: String
  createdAt: Timestamp!
}

type BankAccount @table {
  user: User!
  bankName: String!
  bankUrl: String
  logo: String
  accountNumber: String
  accountNumberMasked: String!
  connectionStatus: String!
  requiresOtp: Boolean
  accountType: String
  lastSyncedAt: Timestamp
  createdAt: Timestamp!
}

type DownloadSchedule @table {
  user: User!
  bankAccount: BankAccount!
  frequency: String!
  scheduledTime: String
  targetFolder: String
  storageType: String
  nextDownloadAt: Timestamp!
  isActive: Boolean!
  statementFormat: String
  startDateOffset: String
  createdAt: Timestamp!
  lastDownloadAt: Timestamp
}

type Statement @table {
  user: User!
  bankAccount: BankAccount!
  downloadSchedule: DownloadSchedule
  fileName: String!
  downloadDate: Timestamp!
  statementPeriodStart: Date!
  statementPeriodEnd: Date!
  fileRef: String!
  status: String
  errorMessage: String
}

type Notification @table {
  user: User!
  message: String!
  type: String!
  createdAt: Timestamp!
  isRead: Boolean!
  relatedStatementId: UUID
}